/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.ControladorPersonal;
import entidades.BaseDatosResultados;
import entidades.Personal;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author UNDC-USI
 */
public class AgregarPersonal extends javax.swing.JInternalFrame {
     private ControladorPersonal cpersonal;
     DefaultTableModel modelo = new DefaultTableModel();
     private boolean edit = false;
     public static boolean PULSARON_BTN_MODIFICAR = false; 

    /**
     * Creates new form AgregarPersonal
     */
    public AgregarPersonal() {
        initComponents();
        
        this.configTable();
        this.cpersonal = new ControladorPersonal();
        this.tablaPersonal();

    }
    
    public String radioSelect(){
        if(radiofijo.isSelected()){
            return radiofijo.getText();
        }else{
            return radiovolante.getText();
        }
    }
    public void configTable(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Fecha_I");
        modelo.addColumn("Tipo");
        this.tabla.setModel(modelo);
    }
    public void tablaPersonal(){ 
        ArrayList informacion = new ArrayList();
        informacion = cpersonal.mostrarPersonal();
        Iterator it = informacion.iterator();
        while(it.hasNext()){
                //Object  ob = it.next();
        Personal p = (Personal) it.next();
        this.modelo.addRow(p.toArray());
            System.out.println(p.getNombre());
        }
        this.tabla.setModel(this.modelo);
    }
    private void clearTable(){
       for (int i = 0; i < tabla.getRowCount(); i++) {
           this.modelo.removeRow(i);
           i-=1;
       }
   }
    public String edit(String id){
        return id;
    }
    public Personal getEntityByRow(String rowid,String nombre,String apellido,String fecha, String tipo){
        Personal tmppersonal = new Personal();
        tmppersonal.setCod_p(rowid);
        tmppersonal.setNombre(nombre);
        tmppersonal.setApellido(apellido);
        tmppersonal.setFecha_i(fecha);
        tmppersonal.setTipo(tipo);
        return tmppersonal;
    }
    public Personal getEntityByRowId(String rowid){
        Personal tmppersonal = new Personal();
        tmppersonal.setCod_p(rowid);
        return tmppersonal;
    }
    public void clearCajas(){
        txtcodigo.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtfecha.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupRadio = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radiofijo = new javax.swing.JRadioButton();
        radiovolante = new javax.swing.JRadioButton();
        txtfecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        jLabel2.setText("Codigo:");

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tipo:"));
        jPanel2.setLayout(null);

        GroupRadio.add(radiofijo);
        radiofijo.setText("Fijo");
        radiofijo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radiofijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiofijoActionPerformed(evt);
            }
        });
        jPanel2.add(radiofijo);
        radiofijo.setBounds(10, 20, 50, 26);

        GroupRadio.add(radiovolante);
        radiovolante.setText("Volante");
        radiovolante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(radiovolante);
        radiovolante.setBounds(100, 20, 70, 26);

        jLabel1.setText("Fecha Ingreso:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(txtfecha)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento"));

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void radiofijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiofijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiofijoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        if(this.PULSARON_BTN_MODIFICAR){
                int opcion = JOptionPane.showConfirmDialog(null,"¿Estas seguro modificar los datos?","Modificar Personal", JOptionPane.YES_NO_OPTION);
                if (opcion == JOptionPane.YES_OPTION)
                {
                    try {
                    Personal tmpersonal = new Personal();
                    tmpersonal.setCod_p(txtcodigo.getText());
                    tmpersonal.setNombre(txtnombre.getText());
                    tmpersonal.setApellido(txtapellido.getText());
                    tmpersonal.setFecha_i(txtfecha.getText());
                    tmpersonal.setTipo(this.radioSelect());

                    int resultado = this.cpersonal.modificarPersonal(tmpersonal);
                        if (resultado == BaseDatosResultados.EXITO_GUARDAR) {
                            this.clearTable();
                            this.tablaPersonal();
                            this.PULSARON_BTN_MODIFICAR = false;
                            this.clearCajas();    
                        }
                        else{
                        JOptionPane.showMessageDialog(null,"Los datos son incorrectos.");
                        }

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null,"No se pudo modificar los datos de la bd,comunicarse con el administrador.");
                    }
                }
        }else{
        try {
            Personal tempersonal = new Personal();
            tempersonal.setCod_p(txtcodigo.getText());
            tempersonal.setNombre(txtnombre.getText());
            tempersonal.setApellido(txtapellido.getText());
            tempersonal.setFecha_i(txtfecha.getText());
            tempersonal.setTipo(this.radioSelect());
            
            int resultado = cpersonal.guardarPersonal(tempersonal);
            
            if(resultado == BaseDatosResultados.EXITO_GUARDAR){
                JOptionPane.showMessageDialog(null,"Se guardo exitosamente al personal.");
                this.clearTable();
                this.tablaPersonal();
                this.clearCajas();
            }else{
                JOptionPane.showMessageDialog(null,"Verificar los datos del personal.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Fallo la insercion de datos, comunicarse con el administrador.");
        }
            
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add yours handling code here:
        
        int row = tabla.getSelectedRow();
        String id =tabla.getValueAt(row, 0).toString();
        String nombre = tabla.getValueAt(row, 1).toString();
        String apellido = tabla.getValueAt(row, 2).toString();
        String fecha = tabla.getValueAt(row, 3).toString();
        String tipo = tabla.getValueAt(row, 4).toString();
        
        Personal p = (Personal) this.getEntityByRow(id,nombre,apellido,fecha,tipo);
        txtcodigo.setText(p.getCod_p());
        txtnombre.setText(p.getNombre());
        txtapellido.setText(p.getApellido());
        txtfecha.setText(p.getFecha_i());
        if(p.getTipo().equals("Fijo")){
            radiofijo.setSelected(true);
        }else{
            radiovolante.setSelected(true);
        }
        this.PULSARON_BTN_MODIFICAR = true;
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int row = tabla.getSelectedRow();
        String id =tabla.getValueAt(row, 0).toString();
        Personal p = (Personal) this.getEntityByRowId(id);
        int opcion = JOptionPane.showConfirmDialog(null,"¿Esta seguro de eliminar al personal "+id+"?","Eliminar Personal", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION){
            int resultado = this.cpersonal.eliminarPersonal(p);
            if(resultado == BaseDatosResultados.EXITO_GUARDAR){
                this.clearTable();
                this.tablaPersonal();
            }else{
                JOptionPane.showMessageDialog(null,"Error al eliminar de la bd, comunicarse con el administrador.");
            }
        }
                
    }//GEN-LAST:event_btnEliminarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupRadio;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    public static javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiofijo;
    private javax.swing.JRadioButton radiovolante;
    public static javax.swing.JTable tabla;
    public static javax.swing.JTextField txtapellido;
    public static javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtfecha;
    public static javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
