/* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author UNDC-USI
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Prueba2
     */
    public Vista() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMantenimiento = new javax.swing.JMenu();
        menuPersonal = new javax.swing.JMenuItem();
        menuGalpon = new javax.swing.JMenuItem();
        menuAsistencia = new javax.swing.JMenu();
        menuItemAsistencia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio);

        menuMantenimiento.setText("Mantenimiento");

        menuPersonal.setText(" Personal");
        menuPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPersonalActionPerformed(evt);
            }
        });
        menuMantenimiento.add(menuPersonal);

        menuGalpon.setText("Galpon");
        menuGalpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGalponActionPerformed(evt);
            }
        });
        menuMantenimiento.add(menuGalpon);

        jMenuBar1.add(menuMantenimiento);

        menuAsistencia.setText("Asistencia");
        menuAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAsistenciaActionPerformed(evt);
            }
        });

        menuItemAsistencia.setText("Generar Asistencia");
        menuItemAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAsistenciaActionPerformed(evt);
            }
        });
        menuAsistencia.add(menuItemAsistencia);

        jMenuBar1.add(menuAsistencia);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPersonalActionPerformed
        // TODO add your handling code here:
        AgregarPersonal p = new AgregarPersonal();
        escritorio.add(p);
        p.show();
        
    }//GEN-LAST:event_menuPersonalActionPerformed

    private void menuGalponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGalponActionPerformed
        // TODO add your handling code here:
        System.out.println("asdasdqeqe");
    }//GEN-LAST:event_menuGalponActionPerformed

    private void menuAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAsistenciaActionPerformed

    private void menuItemAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAsistenciaActionPerformed
        // TODO add your handling code here:
        FormAsistencias frmAsistencia = new FormAsistencias();
        escritorio.add(frmAsistencia);
        frmAsistencia.show();
    }//GEN-LAST:event_menuItemAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAsistencia;
    private javax.swing.JMenuItem menuGalpon;
    private javax.swing.JMenuItem menuItemAsistencia;
    private javax.swing.JMenu menuMantenimiento;
    public static javax.swing.JMenuItem menuPersonal;
    // End of variables declaration//GEN-END:variables
}
